spring:
  datasource:
    url: ${DB_URL:${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-blue-recipe-aef4kc2p-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require}}}
    username: ${DB_USERNAME:${DATABASE_USERNAME:${SPRING_DATASOURCE_USERNAME:neondb_owner}}}
    password: ${DB_PASSWORD:${DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:npg_jpAuI1r6oYKZ}}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:${RABBITMQ_HOST:localhost}}
    port: ${SPRING_RABBITMQ_PORT:${RABBITMQ_PORT:5672}}
    username: ${SPRING_RABBITMQ_USERNAME:${RABBITMQ_USER:guest}}
    password: ${SPRING_RABBITMQ_PASSWORD:${RABBITMQ_PASSWORD:guest}}
    listener:
      simple:
        auto-startup: ${RABBITMQ_ENABLED:false}

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: ${EUREKA_ENABLED:false}
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

app:
  rabbitmq:
    enabled: ${RABBITMQ_ENABLED:false}
    jd-queue: "jd.analysis.queue"
    jd-exchange: "jd.analysis.exchange"
    jd-routing-key: "jd.analysis.routingKey"
  jwt:
    secret: ${JWT_SECRET:3cfa76f28682c3c4321742487421376824138764213876481237648123764812374682314768231}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  upload:
    dir: "./uploads"
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY:AIzaSyA7OQ2ixs-NlJvKK6GTNvX9TF-8JFToNww}
      url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
